/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.commons.lang3.StringUtils;

public class App {

    public String getGreeting() {
        return StringUtils.capitalize("hola mundo");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
